-- MySQL Script generated by MySQL Workbench
-- 04/13/18 18:07:29
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Usuario` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(45) NOT NULL,
  `Masp` VARCHAR(10) NOT NULL,
  `Senha` VARCHAR(20) NOT NULL,
  `Inativo` TINYINT(1) NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Curso` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cadtcc`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cadtcc` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Autor` VARCHAR(45) NOT NULL,
  `Titulo` VARCHAR(200) NOT NULL,
  `Registo` VARCHAR(45) NULL,
  `IdCurso` INT NOT NULL,
  `Ano` VARCHAR(10) NULL,
  `DataEntrega` VARCHAR(10) NULL,
  `DataApersentacao` VARCHAR(10) NULL,
  `Trabalho` VARCHAR(25) NULL,
  PRIMARY KEY (`Id`),
  INDEX `fk_Cadtcc_Curso_idx` (`IdCurso` ASC),
  CONSTRAINT `fk_Cadtcc_Curso`
    FOREIGN KEY (`IdCurso`)
    REFERENCES `mydb`.`Curso` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Log`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Log` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Acao` VARCHAR(45) NOT NULL,
  `IdUsuario` INT NOT NULL,
  `Hora` VARCHAR(10) NOT NULL,
  `Data` VARCHAR(10) NOT NULL,
  `TituloTrabalho` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`Id`),
  INDEX `fk_Log_Usuario1_idx` (`IdUsuario` ASC),
  CONSTRAINT `fk_Log_Usuario1`
    FOREIGN KEY (`IdUsuario`)
    REFERENCES `mydb`.`Usuario` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
