-- MySQL Script generated by MySQL Workbench
-- 04/18/18 14:01:46
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema CADTCC
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema CADTCC
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `CADTCC` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `CADTCC` ;

-- -----------------------------------------------------
-- Table `CADTCC`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CADTCC`.`Usuario` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(45) NOT NULL,
  `Masp` VARCHAR(10) NOT NULL,
  `Senha` VARCHAR(20) NOT NULL,
  `Admin` TINYINT(1) NULL,
  `Inativo` TINYINT(1) NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CADTCC`.`Curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CADTCC`.`Curso` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CADTCC`.`Cadtcc`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CADTCC`.`Cadtcc` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Autor` VARCHAR(45) NOT NULL,
  `Titulo` VARCHAR(200) NOT NULL,
  `Orientador` VARCHAR(45) NULL,
  `Coorientador` VARCHAR(45) NULL,
  `IdCurso` INT NOT NULL,
  `Registro` VARCHAR(45) NULL,
  `DataEntrega` VARCHAR(10) NULL,
  `DataApresentacao` VARCHAR(10) NULL,
  `Trabalho` VARCHAR(25) NULL,
  PRIMARY KEY (`Id`),
  INDEX `fk_Cadtcc_Curso1_idx` (`IdCurso` ASC),
  CONSTRAINT `fk_Cadtcc_Curso1`
    FOREIGN KEY (`IdCurso`)
    REFERENCES `CADTCC`.`Curso` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CADTCC`.`Log`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CADTCC`.`Log` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Acao` VARCHAR(45) NOT NULL,
  `IdUsuario` INT NOT NULL,
  `Hora` VARCHAR(10) NOT NULL,
  `Data` VARCHAR(10) NOT NULL,
  `TituloTrabalho` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`Id`),
  INDEX `fk_Log_Usuario1_idx` (`IdUsuario` ASC),
  CONSTRAINT `fk_Log_Usuario1`
    FOREIGN KEY (`IdUsuario`)
    REFERENCES `CADTCC`.`Usuario` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
