/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author Leandro
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        pnlFundo = new javax.swing.JPanel();
        pnlFundoLabelLogin = new javax.swing.JPanel();
        lblTituloLogin = new javax.swing.JLabel();
        imgLogin = new javax.swing.JLabel();
        lblLogin = new javax.swing.JLabel();
        imgSenha = new javax.swing.JLabel();
        txtLogin = new javax.swing.JTextField();
        lblLogin1 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        setMaximumSize(new java.awt.Dimension(590, 280));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(590, 280));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlFundo.setBackground(new java.awt.Color(249, 249, 249));
        pnlFundo.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEmptyBorder(8, 8, 8, 8), javax.swing.BorderFactory.createLineBorder(new java.awt.Color(59, 110, 143), 2)));
        pnlFundo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlFundoLabelLogin.setBackground(new java.awt.Color(59, 110, 143));
        pnlFundoLabelLogin.setLayout(new java.awt.GridLayout());

        lblTituloLogin.setBackground(new java.awt.Color(206, 218, 227));
        lblTituloLogin.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        lblTituloLogin.setForeground(new java.awt.Color(233, 233, 236));
        lblTituloLogin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTituloLogin.setText("Login");
        pnlFundoLabelLogin.add(lblTituloLogin);

        pnlFundo.add(pnlFundoLabelLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 570, 60));

        imgLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/iconmonstr-user-7-24.png"))); // NOI18N
        pnlFundo.add(imgLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 120, -1, -1));

        lblLogin.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        lblLogin.setForeground(new java.awt.Color(29, 31, 40));
        lblLogin.setText("MASP");
        pnlFundo.add(lblLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, -1, -1));

        imgSenha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/iconmonstr-password-10-24.png"))); // NOI18N
        imgSenha.setToolTipText("Digite o MASP");
        pnlFundo.add(imgSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 180, -1, -1));

        txtLogin.setBackground(new java.awt.Color(249, 249, 249));
        txtLogin.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtLogin.setForeground(new java.awt.Color(29, 31, 40));
        txtLogin.setText("oalka");
        txtLogin.setToolTipText("Digite seu MASP");
        txtLogin.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(59, 110, 149)), javax.swing.BorderFactory.createEmptyBorder(1, 40, 0, 1)));
        txtLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLoginActionPerformed(evt);
            }
        });
        pnlFundo.add(txtLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, 260, 30));

        lblLogin1.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        lblLogin1.setForeground(new java.awt.Color(29, 31, 40));
        lblLogin1.setText("Senha");
        pnlFundo.add(lblLogin1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 160, -1, -1));

        jPasswordField1.setBackground(new java.awt.Color(249, 249, 249));
        jPasswordField1.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jPasswordField1.setForeground(new java.awt.Color(29, 31, 40));
        jPasswordField1.setText("txtSenha");
        jPasswordField1.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(59, 110, 143)), javax.swing.BorderFactory.createEmptyBorder(1, 40, 0, 1)));
        pnlFundo.add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, 260, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/Logo_vertical.png"))); // NOI18N
        pnlFundo.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, -1));

        getContentPane().add(pnlFundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, 280));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel imgLogin;
    private javax.swing.JLabel imgSenha;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JLabel lblLogin;
    private javax.swing.JLabel lblLogin1;
    private javax.swing.JLabel lblTituloLogin;
    private javax.swing.JPanel pnlFundo;
    private javax.swing.JPanel pnlFundoLabelLogin;
    private javax.swing.JTextField txtLogin;
    // End of variables declaration//GEN-END:variables
}
